export const AVANZA_URLS: Record<string, string> = {
  // Large Cap
  "ERIC B":   "https://www.avanza.se/aktier/om-aktien.html/5240/ericsson-b",
  "VOLV B":   "https://www.avanza.se/aktier/om-aktien.html/5269/volvo-b",
  "VOLV A":   "https://www.avanza.se/aktier/om-aktien.html/5268/volvo-a",
  "INVE B":   "https://www.avanza.se/aktier/om-aktien.html/5247/investor-b",
  "SEB A":    "https://www.avanza.se/aktier/om-aktien.html/5255/seb-a",
  "SHB A":    "https://www.avanza.se/aktier/om-aktien.html/5264/handelsbanken-a",
  "SWED A":   "https://www.avanza.se/aktier/om-aktien.html/5241/swedbank-a",
  "AZN":      "https://www.avanza.se/aktier/om-aktien.html/5361/astrazeneca",
  "ATCO A":   "https://www.avanza.se/aktier/om-aktien.html/5234/atlas-copco-a",
  "ATCO B":   "https://www.avanza.se/aktier/om-aktien.html/5235/atlas-copco-b",
  "ABB":      "https://www.avanza.se/aktier/om-aktien.html/5447/abb",
  "ALFA":     "https://www.avanza.se/aktier/om-aktien.html/5580/alfa-laval",
  "SAND":     "https://www.avanza.se/aktier/om-aktien.html/5471/sandvik",
  "SKF B":    "https://www.avanza.se/aktier/om-aktien.html/5259/skf-b",
  "HEXA B":   "https://www.avanza.se/aktier/om-aktien.html/5286/hexagon-b",
  "NIBE B":   "https://www.avanza.se/aktier/om-aktien.html/5325/nibe-industrier-b",
  "BOL":      "https://www.avanza.se/aktier/om-aktien.html/5564/boliden",
  "TELE2 B":  "https://www.avanza.se/aktier/om-aktien.html/5386/tele2-b",
  "TELIA":    "https://www.avanza.se/aktier/om-aktien.html/5479/telia-company",
  "HM B":     "https://www.avanza.se/aktier/om-aktien.html/5364/h-m-b",
  "ASSA B":   "https://www.avanza.se/aktier/om-aktien.html/5271/assa-abloy-b",
  "ESSITY B": "https://www.avanza.se/aktier/om-aktien.html/764241/essity-b",
  "LUND B":   "https://www.avanza.se/aktier/om-aktien.html/5375/lundbergforetagen-b",
  "GETI B":   "https://www.avanza.se/aktier/om-aktien.html/5282/getinge-b",
  "HUSQ B":   "https://www.avanza.se/aktier/om-aktien.html/45189/husqvarna-b",
  "LIFCO B":  "https://www.avanza.se/aktier/om-aktien.html/520898/lifco-b",
  "LOOMIS":   "https://www.avanza.se/aktier/om-aktien.html/154930/loomis",
  "NDA SE":   "https://www.avanza.se/aktier/om-aktien.html/5249/nordea-bank",
  "SCA B":    "https://www.avanza.se/aktier/om-aktien.html/5263/sca-b",
  "SECU B":   "https://www.avanza.se/aktier/om-aktien.html/5270/securitas-b",
  "SWEC B":   "https://www.avanza.se/aktier/om-aktien.html/5409/sweco-b",
  "TREL B":   "https://www.avanza.se/aktier/om-aktien.html/5267/trelleborg-b",
  "EQT":      "https://www.avanza.se/aktier/om-aktien.html/956272/eqt",
  "AXFO":     "https://www.avanza.se/aktier/om-aktien.html/5465/axfood",
  "AAK":      "https://www.avanza.se/aktier/om-aktien.html/26268/aak",
  "CAST":     "https://www.avanza.se/aktier/om-aktien.html/5353/castellum",
  "ELUX B":   "https://www.avanza.se/aktier/om-aktien.html/5238/electrolux-b",
  "INDU C":   "https://www.avanza.se/aktier/om-aktien.html/5245/industrivarden-c",
  "KINV B":   "https://www.avanza.se/aktier/om-aktien.html/5369/kinnevik-b",
  "ALIV SDB": "https://www.avanza.se/aktier/om-aktien.html/5236/autoliv-sdb",
  "EKTA B":   "https://www.avanza.se/aktier/om-aktien.html/5280/elekta-b",
  // Watchlist-aktier
  "EVO":      "https://www.avanza.se/aktier/om-aktien.html/549768/evolution",
  "SINCH":    "https://www.avanza.se/aktier/om-aktien.html/599956/sinch",
  "EMBRAC B": "https://www.avanza.se/aktier/om-aktien.html/707695/embracer-group-b",
  "HTRO":     "https://www.avanza.se/aktier/om-aktien.html/299737/hexatronic-group",
  "SSAB B":   "https://www.avanza.se/aktier/om-aktien.html/495284/ssab-b",
  // Mid Cap
  "BETS B":   "https://www.avanza.se/aktier/om-aktien.html/5482/betsson-b",
  "LATO B":   "https://www.avanza.se/aktier/om-aktien.html/5321/latour-b",
  "NOLA B":   "https://www.avanza.se/aktier/om-aktien.html/5327/nolato-b",
  "PEAB B":   "https://www.avanza.se/aktier/om-aktien.html/5330/peab-b",
  "XVIVO":    "https://www.avanza.se/aktier/om-aktien.html/376275/xvivo-perfusion",
  "THULE":    "https://www.avanza.se/aktier/om-aktien.html/521491/thule-group",
  "HUFV A":   "https://www.avanza.se/aktier/om-aktien.html/5287/hufvudstaden-a",
  "SAGAX B":  "https://www.avanza.se/aktier/om-aktien.html/405815/sagax-b",
  "WALL B":   "https://www.avanza.se/aktier/om-aktien.html/5344/wallenstam-b",
  "INDT":     "https://www.avanza.se/aktier/om-aktien.html/26607/indutrade",
  "JM":       "https://www.avanza.se/aktier/om-aktien.html/5501/jm",
  "BURE":     "https://www.avanza.se/aktier/om-aktien.html/5277/bure-equity",
  "HMS":      "https://www.avanza.se/aktier/om-aktien.html/98412/hms-networks",
  "NCAB":     "https://www.avanza.se/aktier/om-aktien.html/856458/ncab-group",
  "NYFOSA":   "https://www.avanza.se/aktier/om-aktien.html/907825/nyfosa",
  "OEM B":    "https://www.avanza.se/aktier/om-aktien.html/5329/oem-international-b",
  "PNDX B":   "https://www.avanza.se/aktier/om-aktien.html/720476/pandox-b",
  "RATO B":   "https://www.avanza.se/aktier/om-aktien.html/5397/ratos-b",
  "VBG B":    "https://www.avanza.se/aktier/om-aktien.html/5342/vbg-group-b",
  "ADDT B":   "https://www.avanza.se/aktier/om-aktien.html/5537/addtech-b",
  "FABG":     "https://www.avanza.se/aktier/om-aktien.html/5300/fabege",
  "TOBS B":   "https://www.avanza.se/aktier/om-aktien.html/625680/tobii-b",
};
