export const AVANZA_URLS: Record<string, string> = {
  "AAK": "https://www.avanza.se/aktier/om-aktien.html/26268/aak",
  "ABB": "https://www.avanza.se/aktier/om-aktien.html/5447/abb",
  "AFRY": "https://www.avanza.se/aktier/om-aktien.html/5765/afry",
  "ALFA": "https://www.avanza.se/aktier/om-aktien.html/5580/alfa-laval",
  "ALIV SDB": "https://www.avanza.se/aktier/om-aktien.html/5236/autoliv-sdb",
  "ASSA B": "https://www.avanza.se/aktier/om-aktien.html/5271/assa-abloy-b",
  "ATCO A": "https://www.avanza.se/aktier/om-aktien.html/5234/atlas-copco-a",
  "ATCO B": "https://www.avanza.se/aktier/om-aktien.html/5235/atlas-copco-b",
  "AZN": "https://www.avanza.se/aktier/om-aktien.html/5361/astrazeneca",
  "AXFO": "https://www.avanza.se/aktier/om-aktien.html/5465/axfood",
  "BALD B": "https://www.avanza.se/aktier/om-aktien.html/5519/balder-b",
  "BILL": "https://www.avanza.se/aktier/om-aktien.html/5253/billerud",
  "BOL": "https://www.avanza.se/aktier/om-aktien.html/5564/boliden",
  "CAST": "https://www.avanza.se/aktier/om-aktien.html/5353/castellum",
  "DOME": "https://www.avanza.se/aktier/om-aktien.html/549782/dometic-group",
  "EKTA B": "https://www.avanza.se/aktier/om-aktien.html/5280/elekta-b",
  "ELUX B": "https://www.avanza.se/aktier/om-aktien.html/5238/electrolux-b",
  "EMBRAC B": "https://www.avanza.se/aktier/om-aktien.html/707695/embracer-group-b",
  "EPRO A": "https://www.avanza.se/aktier/om-aktien.html/831540/epiroc-a",
  "EPRO B": "https://www.avanza.se/aktier/om-aktien.html/831541/epiroc-b",
  "EQT": "https://www.avanza.se/aktier/om-aktien.html/956272/eqt",
  "ERIC B": "https://www.avanza.se/aktier/om-aktien.html/5240/ericsson-b",
  "ESSITY B": "https://www.avanza.se/aktier/om-aktien.html/764241/essity-b",
  "EVO": "https://www.avanza.se/aktier/om-aktien.html/549768/evolution",
  "GETI B": "https://www.avanza.se/aktier/om-aktien.html/5282/getinge-b",
  "HEXA B": "https://www.avanza.se/aktier/om-aktien.html/5286/hexagon-b",
  "HM B": "https://www.avanza.se/aktier/om-aktien.html/5364/h-m-b",
  "HOLMEN B": "https://www.avanza.se/aktier/om-aktien.html/5244/holmen-b",
  "HPOL B": "https://www.avanza.se/aktier/om-aktien.html/39498/hexpol-b",
  "HUSQ B": "https://www.avanza.se/aktier/om-aktien.html/45189/husqvarna-b",
  "INDU C": "https://www.avanza.se/aktier/om-aktien.html/5245/industrivarden-c",
  "INDT": "https://www.avanza.se/aktier/om-aktien.html/26607/indutrade",
  "INVE B": "https://www.avanza.se/aktier/om-aktien.html/5247/investor-b",
  "INTRUM": "https://www.avanza.se/aktier/om-aktien.html/5223/intrum",
  "KINV B": "https://www.avanza.se/aktier/om-aktien.html/5369/kinnevik-b",
  "LAGR B": "https://www.avanza.se/aktier/om-aktien.html/5514/lagercrantz-group-b",
  "LATO B": "https://www.avanza.se/aktier/om-aktien.html/5321/latour-b",
  "LIFCO B": "https://www.avanza.se/aktier/om-aktien.html/520898/lifco-b",
  "LOOMIS": "https://www.avanza.se/aktier/om-aktien.html/154930/loomis",
  "LUND B": "https://www.avanza.se/aktier/om-aktien.html/5375/lundbergforetagen-b",
  "MTRS": "https://www.avanza.se/aktier/om-aktien.html/753399/munters-group",
  "NDA SE": "https://www.avanza.se/aktier/om-aktien.html/5249/nordea-bank",
  "NIBE B": "https://www.avanza.se/aktier/om-aktien.html/5325/nibe-industrier-b",
  "SAAB B": "https://www.avanza.se/aktier/om-aktien.html/5260/saab-b",
  "SAND": "https://www.avanza.se/aktier/om-aktien.html/5471/sandvik",
  "SBB B": "https://www.avanza.se/aktier/om-aktien.html/808046/sbb-b",
  "SCA B": "https://www.avanza.se/aktier/om-aktien.html/5263/sca-b",
  "SEB A": "https://www.avanza.se/aktier/om-aktien.html/5255/seb-a",
  "SECU B": "https://www.avanza.se/aktier/om-aktien.html/5270/securitas-b",
  "SECT B": "https://www.avanza.se/aktier/om-aktien.html/16226/sectra-b",
  "SHB A": "https://www.avanza.se/aktier/om-aktien.html/5264/handelsbanken-a",
  "SINCH": "https://www.avanza.se/aktier/om-aktien.html/599956/sinch",
  "SKF B": "https://www.avanza.se/aktier/om-aktien.html/5259/skf-b",
  "SOBI": "https://www.avanza.se/aktier/om-aktien.html/5576/swedish-orphan-biovitrum",
  "SSAB A": "https://www.avanza.se/aktier/om-aktien.html/5261/ssab-a",
  "SSAB B": "https://www.avanza.se/aktier/om-aktien.html/495284/ssab-b",
  "STE R": "https://www.avanza.se/aktier/om-aktien.html/5256/stora-enso-r",
  "SWEC B": "https://www.avanza.se/aktier/om-aktien.html/5409/sweco-b",
  "SWED A": "https://www.avanza.se/aktier/om-aktien.html/5241/swedbank-a",
  "TELE2 B": "https://www.avanza.se/aktier/om-aktien.html/5386/tele2-b",
  "TELIA": "https://www.avanza.se/aktier/om-aktien.html/5479/telia-company",
  "TIGO SDB": "https://www.avanza.se/aktier/om-aktien.html/5384/millicom-sdb",
  "TREL B": "https://www.avanza.se/aktier/om-aktien.html/5267/trelleborg-b",
  "VOLCAR B": "https://www.avanza.se/aktier/om-aktien.html/1041480/volvo-cars-b",
  "VOLV A": "https://www.avanza.se/aktier/om-aktien.html/5268/volvo-a",
  "VOLV B": "https://www.avanza.se/aktier/om-aktien.html/5269/volvo-b",
  "ACAD": "https://www.avanza.se/aktier/om-aktien.html/560907/academedia",
  "ADDT B": "https://www.avanza.se/aktier/om-aktien.html/5537/addtech-b",
  "AMBEA": "https://www.avanza.se/aktier/om-aktien.html/753387/ambea",
  "ARJO B": "https://www.avanza.se/aktier/om-aktien.html/831548/arjo-b",
  "ATRLJ B": "https://www.avanza.se/aktier/om-aktien.html/5272/atrium-ljungberg-b",
  "BETS B": "https://www.avanza.se/aktier/om-aktien.html/5482/betsson-b",
  "BIOG B": "https://www.avanza.se/aktier/om-aktien.html/5507/biogaia-b",
  "BONAV B": "https://www.avanza.se/aktier/om-aktien.html/764238/bonava-b",
  "BOOZT": "https://www.avanza.se/aktier/om-aktien.html/780423/boozt",
  "BRAV": "https://www.avanza.se/aktier/om-aktien.html/753395/bravida-holding",
  "BUFAB": "https://www.avanza.se/aktier/om-aktien.html/518131/bufab",
  "BURE": "https://www.avanza.se/aktier/om-aktien.html/5277/bure-equity",
  "CAMX": "https://www.avanza.se/aktier/om-aktien.html/521499/camurus",
  "CATE": "https://www.avanza.se/aktier/om-aktien.html/5484/catena",
  "CIBUS": "https://www.avanza.se/aktier/om-aktien.html/867390/cibus-nordic",
  "CINT": "https://www.avanza.se/aktier/om-aktien.html/1061965/cint-group",
  "CLAS B": "https://www.avanza.se/aktier/om-aktien.html/5276/clas-ohlson-b",
  "COOR": "https://www.avanza.se/aktier/om-aktien.html/523418/coor-service-management",
  "CTM": "https://www.avanza.se/aktier/om-aktien.html/5490/cellavision",
  "DIOS": "https://www.avanza.se/aktier/om-aktien.html/45191/dios-fastigheter",
  "ELAN B": "https://www.avanza.se/aktier/om-aktien.html/5485/elanders-b",
  "FABG": "https://www.avanza.se/aktier/om-aktien.html/5300/fabege",
  "GREP": "https://www.avanza.se/aktier/om-aktien.html/510194/granges",
  "HEBA B": "https://www.avanza.se/aktier/om-aktien.html/5506/heba-b",
  "HMS": "https://www.avanza.se/aktier/om-aktien.html/98412/hms-networks",
  "HTRO": "https://www.avanza.se/aktier/om-aktien.html/299737/hexatronic-group",
  "HUFV A": "https://www.avanza.se/aktier/om-aktien.html/5287/hufvudstaden-a",
  "JM": "https://www.avanza.se/aktier/om-aktien.html/5501/jm",
  "KABE B": "https://www.avanza.se/aktier/om-aktien.html/5308/kabe-b",
  "KNOW": "https://www.avanza.se/aktier/om-aktien.html/5515/knowit",
  "LIME": "https://www.avanza.se/aktier/om-aktien.html/867393/lime-technologies",
  "MEKO": "https://www.avanza.se/aktier/om-aktien.html/5324/meko",
  "MEDIO B": "https://www.avanza.se/aktier/om-aktien.html/788849/medicover-b",
  "MYCR": "https://www.avanza.se/aktier/om-aktien.html/5383/mycronic",
  "NCAB": "https://www.avanza.se/aktier/om-aktien.html/856458/ncab-group",
  "NEWA B": "https://www.avanza.se/aktier/om-aktien.html/5326/new-wave-group-b",
  "NOLA B": "https://www.avanza.se/aktier/om-aktien.html/5327/nolato-b",
  "NOTE": "https://www.avanza.se/aktier/om-aktien.html/5328/note",
  "NP3": "https://www.avanza.se/aktier/om-aktien.html/519504/np3-fastigheter",
  "NYFOSA": "https://www.avanza.se/aktier/om-aktien.html/907825/nyfosa",
  "OEM B": "https://www.avanza.se/aktier/om-aktien.html/5329/oem-international-b",
  "PEAB B": "https://www.avanza.se/aktier/om-aktien.html/5330/peab-b",
  "PLAZ B": "https://www.avanza.se/aktier/om-aktien.html/519508/platzer-fastigheter-b",
  "PNDX B": "https://www.avanza.se/aktier/om-aktien.html/720476/pandox-b",
  "RATO B": "https://www.avanza.se/aktier/om-aktien.html/5397/ratos-b",
  "RESURS": "https://www.avanza.se/aktier/om-aktien.html/569437/resurs-holding",
  "RVRC": "https://www.avanza.se/aktier/om-aktien.html/1041388/rvrc-holding",
  "SAGAX B": "https://www.avanza.se/aktier/om-aktien.html/405815/sagax-b",
  "SAVE": "https://www.avanza.se/aktier/om-aktien.html/325295/nordnet",
  "SDIP B": "https://www.avanza.se/aktier/om-aktien.html/784434/sdiptech-b",
  "SYSR": "https://www.avanza.se/aktier/om-aktien.html/956279/synsam-group",
  "THULE": "https://www.avanza.se/aktier/om-aktien.html/521491/thule-group",
  "TOBS B": "https://www.avanza.se/aktier/om-aktien.html/625680/tobii-b",
  "TROAX": "https://www.avanza.se/aktier/om-aktien.html/549766/troax-group",
  "VBG B": "https://www.avanza.se/aktier/om-aktien.html/5342/vbg-group-b",
  "WALL B": "https://www.avanza.se/aktier/om-aktien.html/5344/wallenstam-b",
  "WIHL": "https://www.avanza.se/aktier/om-aktien.html/5345/wihlborgs-fastigheter",
  "XVIVO": "https://www.avanza.se/aktier/om-aktien.html/376275/xvivo-perfusion",
};
